# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EoooApplication',
            fields=[
                ('applicationid', models.IntegerField(primary_key=True, serialize=False)),
                ('requestedamount', models.FloatField()),
                ('appdate', models.DateField()),
                ('apstatus', models.CharField(max_length=30)),
                ('approved', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'eooo_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooBudget',
            fields=[
                ('budgetid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('budate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooData',
            fields=[
                ('dataid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('datadate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooDepartment',
            fields=[
                ('departmentid', models.BooleanField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'eooo_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooEmployee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('esex', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'eooo_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooFapackage',
            fields=[
                ('packageid', models.IntegerField(primary_key=True, serialize=False)),
                ('ptype', models.CharField(max_length=30)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eooo_fapackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooInfor',
            fields=[
                ('sourceid', models.IntegerField(primary_key=True, serialize=False)),
                ('infodate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_infor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooLogistics',
            fields=[
                ('departmentid', models.BooleanField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eooo_logistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooOutreach',
            fields=[
                ('departmentid', models.BooleanField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eooo_outreach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooParent',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('bday', models.DateField()),
                ('psex', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=50)),
                ('income', models.FloatField()),
            ],
            options={
                'db_table': 'eooo_parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooReviewboard',
            fields=[
                ('departmentid', models.BooleanField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eooo_reviewboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooSchool',
            fields=[
                ('school_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'eooo_school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooStudent',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField(unique=True)),
                ('academic_standing', models.CharField(max_length=1)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('income_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eooo_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooAttending',
            fields=[
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooStudent')),
            ],
            options={
                'db_table': 'eooo_attending',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooBecomes',
            fields=[
                ('appid', models.ForeignKey(db_column='appid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooApplication')),
                ('datadescription', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_becomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooDistributedto',
            fields=[
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooStudent')),
                ('ddate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_distributedto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooFillsout',
            fields=[
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooStudent')),
                ('fdate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_fillsout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooUinfof',
            fields=[
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooStudent')),
            ],
            options={
                'db_table': 'eooo_uinfof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EoooUstoresi',
            fields=[
                ('dataid', models.ForeignKey(db_column='dataid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadb.EoooData')),
                ('dadescription', models.CharField(max_length=30)),
                ('sourcedate', models.DateField()),
            ],
            options={
                'db_table': 'eooo_ustoresi',
                'managed': False,
            },
        ),
    ]
